### ISSUE TITLE
[Telementry] Add tracking of code usage

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#263]
- [x] Get access to some cloud resources on AWS
- [x] Get access to some cloud resources on GCP
- [x] Get your own server
- [ ] Provision Resources (this is the hard part.....)
- [ ] Set up fastapi endpoint to accept a json sent from pet2bids

**Comment by bendhouseart** [comment]
Bumping this up and starting to work on sending data to endpoint from pet2bids.
